### ISSUE TITLE
Add support for javascripting.com

### ISSUE THREAD

**Issue by atilacamurca** [willmendesneto/frontend-search#5]
https://javascripting.com they call themselves

> The definitive source of the best JavaScript libraries, frameworks, and plugins.

The search URL must be like https://www.javascripting.com/search?q=react

**Comment by willmendesneto** [comment]
Sorry for delay. This repository was integrated with `oh-my-zsh`. Because this I'm closing this issue here and I'm encouraging you to add this issue and send the code with updates there.
